### PR TITLE
Move starred repositories to bookmarks screen

### PR DESCRIPTION
**Pull request by Tunous**
stars-and-bookmarks

Related to #578, #624 and #725

### CODE REVIEW

**Comment by Tunous** [comment]
Myself I would prefer to have this as a separate entry in the drawer as seen in #578. But decided to create this pull request to hear your opinions.

**Comment by smichel17** [comment]
I would prefer this implementation because, as I said in #695, I think scrollable navigation drawers are terrible ux:

> Having UI elements in a consistent position means I can build muscle memory and navigate faster as I use the app more. A scrollable drawer throws this all away.

**Comment by maniac103** [comment]
I don't necessarily agree to the scrolling drawer argument (we have _a lot_ of stuff to show, so we probably won't be able to avoid having a scrolling drawer - it's already scrolling in @Tunous example), but I think this implementation is fine, given that having a 'My repositories' + a 'Starred repositories' drawer item is somewhat inconsistent and potentially confusing as well.

**Comment by Tunous** [comment]
So, let's go for #725 and this + close #578 and #624?

**Comment by smichel17** [comment]
> we have a lot of stuff to show, so we probably won't be able to avoid having a scrolling drawer - it's already scrolling in @Tunous example

Also in @Tunous's example, if `Public timeline`, `Trending repos`, and `Github blog` were collapsed into a single entry, it would not scroll. My phone is slightly smaller than that, so we would have to remove those 3 entries (#695), not collapse them, but it's not that far off. However, this is now off-topic for this PR so I'll shut up about it now :)

**Comment by maniac103** [comment]
I just noticed via #684 that this PR in its current state loses sort order options.

**Comment by Tunous** [comment]
Is it OK to add it as submenu similar to the one for filtering notifications? I think that will fit better than right-side menu.

**Comment by maniac103** [comment]
Yeah, it surely is.

**Comment by Tunous** [comment]
Added.

**Comment by Tunous** [comment]
@maniac103 perhaps it's time to decide on what to do with this. I think the option I mentioned [here](https://github.com/slapperwan/gh4a/pull/734#issuecomment-332198696) is the way to go.

**Comment by maniac103** [comment]
This one is fine with me; I have more issues with #725.

**Pull request merged**
