### PR TITLE
Added icons for the main drawer

### PR DESCRIPTION
**Pull request by viktorstrate**
I've added icons for the main drawer, using icons from [Material Design Icons](https://materialdesignicons.com/)

This pull request closes issue #390

Main drawer icons, preview

### CODE REVIEW

**Comment by viktorstrate** [comment]
Some files are missing, I will post a new pull request later

**Comment by Kurre** [comment]
N.B. No need to open a new PR. Just push new commits to the same branch (viktorstrate:feature-icons) or even amend/rebase/what-ever you like. Github will figure it out 🙂

**Comment by viktorstrate** [comment]
Okay, thank you 👍

**Comment by viktorstrate** [comment]
Okay, everything should work now 😉

**Comment by viktorstrate** [comment]
I will send a new PR, because I had to force push

**Pull request closed without merging**
