### PR TITLE
Click targets and highlihts improvements

### PR DESCRIPTION
**Pull request by Tunous**
- Now possible to enter own user screen when clicking anywhere inside of the drawer title instead of just the avatar
- Search suggestions now display click highlight

### CODE REVIEW

**Comment by maniac103** [comment]
+1 for the search suggestion changes, not sure about the nav drawer one though. Actually the current layout is more of a placeholder, and I eventually want it to behave like the Gmail drawer header, in which case the user's name would be removed (see #150). We might be able to kang some code from jruesga/rview for this.

**Comment by Tunous** [comment]
Hmm, I'll leave the implementation of that header for you then as I'm not exactly sure how you want it to work.

You can just cherry-pick the search suggestion changes :)

**Comment by maniac103** [comment]
I've implemented what I had in mind here: https://github.com/slapperwan/gh4a/tree/multi-account

It's mostly working, but the 'add new account' thing still needs a dialog that
- points the user to log out from Github in his browser beforehand and
- shows a indeterminate progress bar after starting the actual oauth process

Comments and patches are welcome ;)

**Comment by Tunous** [comment]
> points the user to log out from Github in his browser beforehand

I found this: https://github.com/logout.

**Comment by maniac103** [comment]
Yeah, sure, that's where the user needs to be pointed to. There's no way to automatically redirect him to the app after logging out, though, just as there's no way to enforcing a new login in the oauth flow :(

**Comment by maniac103** [comment]
Pushed the suggestion background fix and the multi-account branch to master.

**Pull request closed without merging**
