### PR TITLE
Add Chinese translation

### PR DESCRIPTION
**Pull request by xtexChooser**
It adds almost all Chinese translations.
Some words(e.g Fork, Star, Watch) is not translated because they are not needed.
You can look at Chinese open source platform Gitee(gitee.com). They also did not translate these 

words.
I can not understand a few words. They are:
1. First-timer
My understanding:
First-timer=first timer
first = ordinal number one, e.g first floor, second first.
timer = tools for timing
Where does the feature appear?
**It is not translated**

2. Copy number
My understanding:
Copy = Ctrl+C
number = "number" in "telephone number", but what number is this?
I direct translated it, but the meaning may be vague.

### CODE REVIEW

**Comment by maniac103** [comment]
Sorry I completely missed your PR. Let me answer your questions:

> First-timer

This is one of the roles the Github API sends when somebody writes a comment. Other roles include 'Collaborator', 'Contributor' etc. ... see [here](https://docs.github.com/en/graphql/reference/enums#commentauthorassociation) for the explanation on those roles.

> Copy number

This is a menu entry for copying the number of the currently opened issue/PR to the clipboard. In the case of this very PR, it would copy the text '1043' with the label 'Pull Request #1043' to the clipboard.

**Comment by xtexChooser** [comment]
Can I translate `Try again` same as `Retry`?

> Sorry I completely missed your PR. Let me answer your questions:
> 
> > First-timer
> 
> This is one of the roles the Github API sends when somebody writes a comment. Other roles include 'Collaborator', 'Contributor' etc. ... see [here](https://docs.github.com/en/graphql/reference/enums#commentauthorassociation) for the explanation on those roles.
> 
> > Copy number
> 
> This is a menu entry for copying the number of the currently opened issue/PR to the clipboard. In the case of this very PR, it would copy the text '1043' with the label 'Pull Request #1043' to the clipboard.

Thanks, I am checking the translations again. I found many errors. I will commit again

**Comment by maniac103** [comment]
> Can I translate Try again same as Retry?

Yes. It's the retry button shown under the error image when API calls fail (e.g. due to network issues).

**Comment by xtexChooser** [comment]
I reviewed all and improved some translations just now.

`First-timer` and `Copy number` are translated now.

Other changes:
1. Add new strings like `credentials_error_invalid_token`
2. Remove strings did not required to translate like `my_email` `my_web` `my_username` `my_repo` `copyright_notice`
3. Standardize some translation like `issue` to `Issue`
4. Translated word `Tag`
5. And some wrong translations

**Comment by xtexChooser** [comment]
@maniac103 ping

**Comment by maniac103** [comment]
Can you please rebase & update for the latest additions? I'll merge afterwards.

**Comment by xtexChooser** [comment]
> Can you please rebase & update for the latest additions? I'll merge afterwards.

Please wait, I am creating an new fork and an new PR for this

**Pull request closed without merging**
