### PR TITLE
Added icons for the main drawer, updated version

### LINKED ISSUE #390: Icons in the navigation drawer
It could be good, to have icons for every item in the navigation drawer.
I will work on this, using icons from [Material design icons](https://materialdesignicons.com/), if you want? 😄

### PR DESCRIPTION
**Pull request by viktorstrate**
I've added icons for the main drawer, using icons from [Material Design Icons](https://materialdesignicons.com/)
This closes #390

### CODE REVIEW

**Comment by maniac103** [comment]
I'll try this soon, it doesn't work as is though: we'll need pngs of the vector drawables for platform versions < 21.

**Comment by viktorstrate** [comment]
I tried it in API 16, and it seems to work fine, am I missing something??
Screenshot

**Comment by maniac103** [comment]
Huh. Maybe Android Studio does some magic in the background, I'll check. If it did, I could nuke the various other PNG drawables as well.

**Comment by maniac103** [comment]
Heh, Android Studio indeed 'magically' creates pngs for all vector drawables. Approach looks fine then, one learns something new every day :)
Icons look nice generally as well, the only issue I have is with the 'my repositories' one: for repos I've so far used a 'cloud' icon. I think I like yours better, but for consistency, we should update the icon for the repo search type as well. Could you please do that or - alternatively - tell me the name of the icon you used for 'my repositories'?
Also, please don't forget to update anon_nav_drawer.xml.

**Comment by viktorstrate** [comment]
Good to know that with the PNG files :) 
I can update the rest of the icons later today, I don't know this code base very well, so correct me if I miss something here and there.  ;)

**Comment by viktorstrate** [comment]
I've updated the icons in `anon_nav_drawer.xml`, and updated the icon for repo search.

**Comment by maniac103** [comment]
Please also update the dark theme, and delete the old (now unused) repo search icon.

**Comment by viktorstrate** [comment]
Sorry, I forgot 😉 I've updated it

**Pull request merged**
