### PR TITLE
Correctly link pull request files

### LINKED ISSUE #456: Open in browser for pull request file diff links incorrectly
1. View pull request
2. Go to files tab 
3. View diff for a file 
4. Click on the open in browser action 

Currently doing so opens latest pull request commit diff in browser when instead it should open the files diff for the whole pull request. Better yet if it scrolled to that file but that needs [the SHA we don't know](https://github.com/slapperwan/gh4a/issues/413). (Or we do in this case?) 

Example link: https://github.com/slapperwan/gh4a/pull/454/files#diff-ce9de4f775f8605b5ba5a0a0dd200ac3

### PR DESCRIPTION
**Pull request by Tunous**
Closes #456.

### CODE REVIEW

**Comment by maniac103** [comment]
Hmm, this feels a bit inconsistent. The commit URL doesn't have the path, while the PR one does. I'm not sure what version is actually more correct, but I feel they should be consistent.

**Comment by maniac103** [comment]
I also wonder whether createUrl() shouldn't be abstract in DiffViewerActivity.

**Comment by Tunous** [comment]
> The commit URL doesn't have the path, while the PR one does.

Oh yes. I think that the path should be added to commit URL too. That way it will behave like on GitHub web.

> I also wonder whether createUrl() shouldn't be abstract in DiffViewerActivity.

Sure.

**Comment by Tunous** [comment]
Updated.

**Pull request merged**
