### PR TITLE
Fix TransactionTooLargeException when opening a diff with lots of comments

### PR DESCRIPTION
**Pull request by Fs00**
This PR fixes a crash that was occurring when tapping on a file (in PR Files tab) to open the diff in PR PowerShell/PowerShell#9900, caused by a TransactionTooLargeException due to lots of big review comments.
Here I've used the same approach that has been used for the CommitFragment (gzipping the data into the bundle), though I had to write new methods for this specific context. After fixing the issue, I did my best to remove the duplication I had introduced.

### CODE REVIEW

**Comment by maniac103** [comment]
LGTM, but can you please squash the deduplication + type annotation fix commits?

**Comment by Fs00** [comment]
Ok, do you want a single commit for everything or one for the fix + one for the deduplication?

**Comment by maniac103** [comment]
Either is fine.

**Comment by Fs00** [comment]
Squashed.

**Pull request merged**
