### PR TITLE
Improve text sizes in Markdown rendering

### PR DESCRIPTION
**Pull request by Fs00**
I've made a couple of adjustments regarding text sizes to Markdown rendering in comments/Readme:
- <sub>subscript</sub>/<sup>superscript</sup> text is now smaller, to make it look as it does in GitHub web UI
- sizes of H1 to H6 has been changed to make the different types of heading more clearly distinguishable. Previously I had a hard time finding the difference between an H1 and an H2, or between an H2 and an H3. You can see below the difference:
<table>
<tr><th>Before</th><th>After</th></tr>
<tr><td>

</td><td>
</td></tr>
</table>

### CODE REVIEW

**Comment by Fs00** [comment]
@maniac103 Can this be merged too? Any doubts?

**Comment by maniac103** [comment]
The only thing I have doubts about is that I'm not sure about H6 size being smaller than normal text.

**Comment by Fs00** [comment]
I thought it was fine because I've seen that the GitHub UI makes H6 even smaller than we do (on the GH website H6 are 85% of the normal text size compared to 90% in the app).

An alternative I see is to make H6 as big as normal text and H5, but change their color to a dark shade of grey (both the GitHub UI and [our Markdown CSS](https://github.com/slapperwan/gh4a/blob/master/app/src/main/assets/markdown-light.css#L60) use this approach).

**Comment by maniac103** [comment]
If they're doing the same thing it's fine I guess.

**Pull request merged**
